# Site Information
license:           "MIT"
license-url:       "https://github.com/takagotch//LICENSE"
author:            "Blackrock Digital"

# Site Settings
baseurl:           "/page48"

# Build settings
markdown:          kramdown
exclude:           [node_modules]

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Server
url:               "https://takagotch.github.io/page48/"
enforce_ssl:       https://takagotch.github.io/
encoding:          UTF-8
host:              localhost
port:              9000

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-tidy

# Collections
collections:
  themes:
    output:        true
    permalink:     /:collection/:title/
  templates:
    output:        true
    permalink:     /:collection/:title/
  snippets:
    output:        true
    permalink:     /:collection/:title/
  guides:
    output:        true
    permalink:     /:collection/:title/
  previews:
    output:        true
    permalink:     /:collection/:title/
  premium:
    output:        false

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Blog Excerpt Separator
excerpt_separator: "<!--more-->"


